apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cadvisor
  namespace: kube-system
  labels:
    k8s-app: cadvisor
spec:
  selector:
    matchLabels:
      k8s-app: cadvisor
  template:
    metadata:
      labels:
        k8s-app: cadvisor
    spec:
      hostNetwork: true
      hostPID: true
      tolerations:
      - operator: "Exists"
      containers:
      - name: cadvisor
        image: gcr.io/cadvisor/cadvisor:v0.47.2
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          privileged: true
        ports:
        - containerPort: 8080
          hostPort: 8080
          name: http-metrics

        volumeMounts:
        - name: rootfs
          mountPath: /rootfs
          readOnly: true

        - name: sys
          mountPath: /sys
          readOnly: true

        - name: cgroup
          mountPath: /sys/fs/cgroup
          readOnly: true

        - name: var-run
          mountPath: /var/run
          readOnly: false

        - name: docker
          mountPath: /var/lib/containerd
          readOnly: true

        - name: containerd
          mountPath: /var/lib/rancher/k3s/agent/containerd
          readOnly: true

      volumes:
      - name: rootfs
        hostPath:
          path: /

      - name: sys
        hostPath:
          path: /sys

      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup

      - name: docker
        hostPath:
          path: /var/lib/containerd

      - name: var-run
        hostPath:
          path: /var/run


      - name: containerd
        hostPath:
          path: /var/lib/rancher/k3s/agent/containerd
